Repository slackapi/slack-github-action, pull requests merged in 2022-10, with the labels that each got.

#132 Use https proxy agent
  package-lock.json
  package.json
  src/slack-send.js
  test/slack-send-test.js
Labels: enhancement

#139 Release v1.23.0
  README.md
  example-workflows/Technique_1_Slack_Workflow_Builder/JSON_payload.yml
  example-workflows/Technique_1_Slack_Workflow_Builder/JSON_payload_from_file.yml
  example-workflows/Technique_1_Slack_Workflow_Builder/default_GitHub_Trigger_payload.yml
  example-workflows/Technique_2_Slack_App/JSON_payload.yml
  example-workflows/Technique_2_Slack_App/JSON_payload_as_text.yml
  example-workflows/Technique_2_Slack_App/main.yml
  example-workflows/Technique_3_Slack_Incoming_Webhook/main.yml
  package-lock.json
  package.json
Labels: enhancement

#140 Add in testing instructions for maintainer's guide and standardize bullet point punctuation
  .github/maintainers_guide.md
Labels: documentation

#124 Added checks for bot token and webhook url length
  src/slack-send.js
Labels: bug
