Repository slackapi/slack-github-action, pull requests merged in 2023-05, with the labels that each got.

#200 Feature/fix payload file test
  .github/resources/payload-notification.json
  .github/workflows/main.yml
  README.md
  src/slack-send.js
Labels: cla:missing

#201 Update README.md with variable usage and links to example workflows.
  README.md
Labels: documentation

#207 Update payload integration test to escape invalid characters
  .github/workflows/main.yml
Labels: enhancement
