Repository slackapi/slack-github-action, pull requests merged in 2024-12, with the labels that each got.

#371 docs: fix incorrect parameter name in uploadV2 (channel -> channel_id)
  README.md
Labels: cla:signed

#374 fix: avoid erroring if conflicting techniques are set from environment variables
  src/config.js
  src/send.js
  test/config.spec.js
  test/index.spec.js
  test/send.spec.js
Labels: bug, semver:patch

#375 ci: reduce the permissions for github actions jobs
  .github/workflows/develop.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: security, semver:patch, github_actions

#376 docs: showcase updated use cases in example workflows
  README.md
  example-workflows/Technique_1_Slack_Workflow_Builder/JSON_payload.yml
  example-workflows/Technique_1_Slack_Workflow_Builder/JSON_payload_from_file.yml
  example-workflows/Technique_1_Slack_Workflow_Builder/README.md
  example-workflows/Technique_1_Slack_Workflow_Builder/announcements.gha.yml
  example-workflows/Technique_1_Slack_Workflow_Builder/announcements.manifest.json
  example-workflows/Technique_1_Slack_Workflow_Builder/announcements.trigger.json
  example-workflows/Technique_1_Slack_Workflow_Builder/builds.data.json
  example-workflows/Technique_1_Slack_Workflow_Builder/builds.gha.yml
  example-workflows/Technique_1_Slack_Workflow_Builder/builds.manifest.json
  example-workflows/Technique_1_Slack_Workflow_Builder/builds.trigger.json
  example-workflows/Technique_1_Slack_Workflow_Builder/default_GitHub_Trigger_payload.yml
  example-workflows/Technique_1_Slack_Workflow_Builder/payloads/example.json
  example-workflows/Technique_1_Slack_Workflow_Builder/topic.gha.yml
  example-workflows/Technique_1_Slack_Workflow_Builder/topic.manifest.json
  example-workflows/Technique_1_Slack_Workflow_Builder/topic.trigger.json
  example-workflows/Technique_2_Slack_API_Method/README.md
  example-workflows/Technique_2_Slack_API_Method/author.yml
  example-workflows/Technique_2_Slack_API_Method/invite.yml
  example-workflows/Technique_2_Slack_App/JSON_payload.yml
  example-workflows/Technique_2_Slack_App/JSON_payload_as_text.yml
  example-workflows/Technique_2_Slack_App/main.yml
  example-workflows/Technique_3_Slack_Incoming_Webhook/README.md
  example-workflows/Technique_3_Slack_Incoming_Webhook/blocks.yml
  example-workflows/Technique_3_Slack_Incoming_Webhook/saved.data.json
  example-workflows/Technique_3_Slack_Incoming_Webhook/saved.gha.yml
  example-workflows/Technique_3_Slack_Incoming_Webhook/text.yml
Labels: documentation, semver:patch
