Repository slackapi/slack-github-action, pull requests merged in 2024-05, with the labels that each got.

#308 Add codecov coverage uploading
  .github/workflows/main.yml
  .gitignore
  README.md
  package.json
Labels: tests

#309 doc: how to reply to a message
  README.md
  test/slack-send-test.js
Labels: documentation

#310 ci(test): run integration tests in a single sequential environment
  .github/workflows/main.yml
Labels: semver:patch, tests
