Repository slackapi/slack-github-action, pull requests merged in 2025-05, with the labels that each got.

#420 fix: require a custom 'api' url to send to instead of absolute urls as a 'method'
  src/client.js
  test/client.spec.js
  test/index.spec.js
Labels: bug, semver:patch

#431 fix: include cause of parsing errors in action output logs
  src/content.js
  src/errors.js
  src/index.js
  test/content.spec.js
Labels: bug, semver:patch

#438 chore(release): tag version 2.1.0
  docs/additional-configurations.md
  docs/sending-techniques/sending-data-slack-api-method/sending-data-slack-api-method.md
  docs/sending-techniques/sending-data-slack-incoming-webhook/sending-data-slack-incoming-webhook.md
  docs/sending-techniques/sending-data-webhook-slack-workflow/sending-data-webhook-slack-workflow.md
  docs/sending-techniques/sending-techniques.md
  example-workflows/Technique_1_Slack_Workflow_Builder/announcements.gha.yml
  example-workflows/Technique_1_Slack_Workflow_Builder/builds.gha.yml
  example-workflows/Technique_1_Slack_Workflow_Builder/topic.gha.yml
  example-workflows/Technique_2_Slack_API_Method/author.yml
  example-workflows/Technique_2_Slack_API_Method/invite.yml
  example-workflows/Technique_3_Slack_Incoming_Webhook/blocks.yml
  example-workflows/Technique_3_Slack_Incoming_Webhook/saved.gha.yml
  example-workflows/Technique_3_Slack_Incoming_Webhook/text.yml
  package-lock.json
  package.json
Labels: semver:minor, release

#441 ci: pin action hashes and escape variables with minimum permission
  .github/workflows/develop.yml
  .github/workflows/publish.yml
  .github/workflows/sync-docs.yml
  .github/workflows/test.yml
Labels: github_actions

#447 docs: fix channel mention formatting
  docs/sending-techniques/sending-data-slack-api-method/sending-data-slack-api-method.md
Labels: docs, semver:patch
